### ISSUE TITLE
Birthday picker is not an actual date picker

### ISSUE THREAD

**Issue by nudded** [Silox/Eddy#3]
![screen shot 2016-03-15 at 21 48 31](https://cloud.githubusercontent.com/assets/104395/13793556/b44c75ce-eaf7-11e5-97df-435937228fa8.png)

**Comment by Silox** [comment]
It is on my machine:
![screen shot 2016-03-20 at 12 33 41](https://cloud.githubusercontent.com/assets/915130/13904170/02fecab6-ee98-11e5-9606-06e6223ddb93.png)
